language: android

sudo: false

before_cache:
  - rm -rf $HOME/.gradle/caches/*/fileHashes/
  - rm -f $HOME/.gradle/caches/**/*.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - android-28
    - build-tools-27.0.3
licenses:
  - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew

script: ./gradlew clean testReleaseUnitTest assembleRelease

notifications:
  email: false
